Issue #1442: Error Before Confirm Action
layer2tech/mercury-wallet pull request #1475
Opened 2022-05-18 14:47 UTC by sgershuny

Issue #1442: - Error shows before action confirmed on withdrawal and send statecoin

2022-05-19 15:30 UTC, lawlawlaw requested changes
See comment. Please add tests,

2022-05-19 15:30 UTC, lawlawlaw commented on src/features/WalletDataSlice.js
> +  var input_pubkey = "";
The address validity should be checked before the confirmation dialog is shown. Therefore the address should be check in checkWithdrawal().

2022-05-19 18:25 UTC, sgershuny commented on src/features/WalletDataSlice.js
> +  var input_pubkey = "";
I've had to revert the change I made as using the "encodeSCEAddress" function to check a btc address always returns an error

2022-05-24 07:53 UTC, lawlawlaw commented on src/features/WalletDataSlice.js
> +  var input_pubkey = "";
It still doesn't check for a problem with the address before displaying the confirmation dialog.

2022-07-08 12:31 UTC, merged