Fix/move swapped coins
layer2tech/mercury-wallet pull request #1560
Opened 2022-08-01 16:34 UTC by rk16449

1. on load, don't load swapped coins instead put them into an array (in memory) only - completed
2. move them into a swapped array in the file when saving - completed

2022-08-03 09:59 UTC, lawlawlaw reviewed
Approved subject to confirmation that this improves app responsiveness after the wallet has loaded for large wallet files - @tomt1664 will confirm.

2022-08-03 12:20 UTC, lawlawlaw approved these changes

2022-08-03 12:21 UTC, lawlawlaw requested changes
Can you write tests for these changes?

2022-08-05 16:23 UTC, tomt1664 approved these changes

2022-08-07 23:07 UTC, merged