Batch withdraw
layer2tech/mercury-wallet pull request #250
Opened 2021-04-21 13:32 UTC by lawlawlaw

* Enable batch withdrawal by selecting multiple coins in the GUI
* Coin selection is toggled by repeated clicks on the coin listing in the Swap and Withdrawal page. Multiple coins can be selected simultaneously by clicking on each of the required coins.
* Draft pull request: changing to "selected style" via "isSelectedStyle" (changing the coin background to grey) is slow.

2021-04-21 16:33 UTC, 86667 requested changes

2021-04-21 16:33 UTC, 86667 commented on src/components/coins/coins.js
> +function useForceUpdate(){
there is already a way to refresh Coins. Check how `props.refresh` is used and accessed by other Pages.

2021-04-21 16:33 UTC, 86667 commented on src/components/panelCoinsActivity/panelCoinsActivity.js
> +    function setSelectedCoin(statechain_id) {
Lets keep function syntax to be consistent throughout the codebase. 

`const setSelectedCoin = () => {}`

2021-04-21 16:33 UTC, 86667 commented on src/containers/Send/Send.js
> +        prevSelectedCoins => {
Just set selected coin to `statechain_id`? 

```
setSelectedCoins([statechain_id]).
```

Im not sure if Send page should care about the data structures of Coins panel. It only cares about the single selectedCoin. I think it confuses the code to have setSelectedCoins([]) with an array on this page.

2021-04-21 16:33 UTC, 86667 commented on src/settings.json
> +  "state_entity_endpoint": "http://0.0.0.0:8000",
revert

2021-04-22 13:33 UTC, lawlawlaw commented on src/components/panelCoinsActivity/panelCoinsActivity.js
> +    function setSelectedCoin(statechain_id) {
done

2021-04-22 13:34 UTC, lawlawlaw commented on src/settings.json
> +  "state_entity_endpoint": "http://0.0.0.0:8000",
done

2021-04-22 13:34 UTC, lawlawlaw commented on src/containers/Send/Send.js
> +        prevSelectedCoins => {
done

2021-04-22 14:14 UTC, 86667 commented
Thanks for changes. 

Looks good apart from in removig coin from Swap i get 

```
TypeError: Cannot read property 'statechain_id' of undefined

2021-04-22 16:03 UTC, 86667 approved these changes

2021-04-23 14:20 UTC, closed without merging