MW-244: import/export wallet as JSON
layer2tech/mercury-wallet pull request #256
Opened 2021-04-22 14:11 UTC by alexyjs

- https://github.com/layer2tech/mercury-wallet/issues/244

2021-04-22 14:12 UTC, alexyjs commented
@86667 
The main flow of import/export have been done. The next part is to get the exactly wallet data to save to json file. I need your help in this part. Please tell me which function I can use to get that data?

2021-04-22 14:26 UTC, 86667 commented
Im sorry I forgot to mention the the RestorePage need a password input also.

2021-04-22 15:25 UTC, alexyjs commented
![password_input](https://user-images.githubusercontent.com/9798103/115740988-03db6b00-a398-11eb-84dd-e4b418100bb3.png)

@86667 
You mean to add password input like this? Do we need a confirm password also?

2021-04-22 16:36 UTC, 86667 commented
@alexyjs Yes cool. And no, we dont need a confirm box for this one. But still have it as `type="password"` and with the button to turn it into text as it is on the other password textboxes.

2021-04-27 13:19 UTC, alexyjs commented
@86667 
please review this feature

2021-04-27 15:10 UTC, 86667 approved these changes

2021-04-27 15:10 UTC, 86667 commented on src/features/WalletDataSlice.js
> +    wallet_json.mnemonic = decryptAES(wallet_json.mnemonic, password);
Move this decrypting logic into a `Wallet` function so that it can be tested in `wallet.test.js`

When you call Wallet.fromBackupJson (or whatever you call it), you then need to call 
```
  log.info("Wallet "+name+" laoded from backup.");
  if (testing_mode) log.info("Testing mode set.");
  wallet.initElectrumClient(setBlockHeightCallBack);
  callNewSeAddr();
  wallet.save();
```
from witihn `WalletDataSlice`, as with the other wallet load fns `walletLoad` and `walletFromMnemonic`

2021-04-27 15:10 UTC, 86667 requested changes
See above comment

2021-04-27 15:21 UTC, 86667 commented
Another thing is the file explorer doesnt work in built version. I think you need to copy the new code in `electron-starter.js` into `public/electron.js`.

2021-04-28 13:25 UTC, alexyjs commented
@86667 
I have updated following your comments. Please review again.

2021-04-28 14:23 UTC, 86667 commented
@alexyjs Wonderful stuff!

Fic merge conflict and youre good to merge.

2021-05-05 23:06 UTC, merged