chore: open block explorer window
layer2tech/mercury-wallet pull request #574
Opened 2021-07-14 08:15 UTC by rk16449

2021-07-14 13:08 UTC, lawlawlaw requested changes

2021-07-14 13:08 UTC, lawlawlaw commented on src/components/coins/coins.js
> +      window.require("electron").shell.openExternal('https://blockstream.info/tx/'  + txId);
Please use the "testnet" URL (https://blockstream.info/tx/testnet) if using the testnet network.

2021-07-15 08:41 UTC, rk16449 commented on src/components/coins/coins.js
> +      window.require("electron").shell.openExternal('https://blockstream.info/tx/'  + txId);
changes now applied

2021-07-15 12:37 UTC, lawlawlaw approved these changes

2021-07-15 12:57 UTC, merged